import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"

interface ActivitySummaryProps {
  isGenerating: boolean
  lastGeneratedAt: Date | null
  error: Error | null
  onGenerate: () => void
}

export function ActivitySummary({
  isGenerating,
  lastGeneratedAt,
  error,
  onGenerate,
}: ActivitySummaryProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>
          Recent activity — generated by Snowflake AI
        </CardTitle>

        <CardDescription>
          Generate an AI summary of detection activity from
          the last 30 minutes.
        </CardDescription>
      </CardHeader>

      <CardContent className="space-y-4">
        <Button
          onClick={onGenerate}
          disabled={isGenerating}
        >
          {isGenerating
            ? "Generating Summary..."
            : "Generate Summary"}
        </Button>

        {lastGeneratedAt && (
          <p className="text-sm text-muted-foreground">
            Last generated{" "}
            {lastGeneratedAt.toLocaleTimeString()}
          </p>
        )}

        {error && (
          <p
            className="text-sm text-destructive"
            role="alert"
          >
            Unable to generate activity summary.
          </p>
        )}

        {!lastGeneratedAt && !error && (
          <p className="text-sm text-muted-foreground">
            No AI summary has been generated yet.
          </p>
        )}
      </CardContent>
    </Card>
  )
}