import {
  render,
  screen,
  within,
} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {
  describe,
  expect,
  it,
  vi,
} from "vitest";

import { ActivitySummary } from "@/components/ActivitySummary";
import type { SummaryResult } from "@/types/contracts";

const baseProps = {
  analyticsEnabled: true,
  isGenerating: false,
  lastGeneratedAt: null,
  summary: null,
  error: null,
  onGenerate: vi.fn(),
};

const aiSummary: SummaryResult = {
  text: "Two possible knocking detections were counted.",
  event_count: 2,
  counts: { knock: 2 },
  since: "2026-10-02T12:00:00.000Z",
  through: "2026-10-02T12:25:00.000Z",
  generated_at: "2026-10-02T12:30:00.000Z",
  model: "llama3.3-70b",
  query_id: "query-1",
};

describe("ActivitySummary", () => {
  it("renders the AI text, exact counts, and provenance", () => {
    render(
      <ActivitySummary
        {...baseProps}
        summary={aiSummary}
        lastGeneratedAt={new Date("2026-10-02T12:30:00Z")}
      />
    );

    expect(
      screen.getByText(aiSummary.text)
    ).toBeInTheDocument();

    const counts = screen.getByLabelText(
      "Exact detection counts in the summary window"
    );

    expect(
      within(counts).getByText("Knock")
    ).toBeInTheDocument();
    expect(within(counts).getByText("2")).toBeInTheDocument();
    expect(
      within(counts).getByText("Doorbell")
    ).toBeInTheDocument();
    expect(within(counts).getByText("0")).toBeInTheDocument();

    expect(
      screen.getByText("Generated by llama3.3-70b")
    ).toBeInTheDocument();
    expect(
      screen.getByText(/Last generated/)
    ).toBeInTheDocument();
  });

  it("does not claim an AI call for empty summaries", () => {
    const empty: SummaryResult = {
      ...aiSummary,
      text: "No permitted detector events were found in the requested window.",
      event_count: 0,
      counts: {},
      model: null,
      query_id: null,
    };

    render(
      <ActivitySummary {...baseProps} summary={empty} />
    );

    expect(
      screen.getByText(empty.text)
    ).toBeInTheDocument();
    expect(
      screen.getByText(/No AI model was used/)
    ).toBeInTheDocument();
    expect(
      screen.queryByText(/Generated by/)
    ).not.toBeInTheDocument();
  });

  it("disables generation without analytics consent", () => {
    render(
      <ActivitySummary
        {...baseProps}
        analyticsEnabled={false}
      />
    );

    expect(
      screen.getByRole("button", {
        name: "Generate Summary",
      })
    ).toBeDisabled();

    expect(
      screen.getByText(
        /Enable analytics and cloud storage in settings/
      )
    ).toBeInTheDocument();
  });

  it("generates a summary when enabled", async () => {
    const user = userEvent.setup();
    const onGenerate = vi.fn();

    render(
      <ActivitySummary
        {...baseProps}
        onGenerate={onGenerate}
      />
    );

    await user.click(
      screen.getByRole("button", {
        name: "Generate Summary",
      })
    );

    expect(onGenerate).toHaveBeenCalledOnce();
  });

  it("shows the error state", () => {
    render(
      <ActivitySummary
        {...baseProps}
        error={new Error("boom")}
      />
    );

    expect(
      screen.getByRole("alert")
    ).toHaveTextContent(
      "Unable to generate activity summary."
    );
  });
});
