import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import type { SummaryResult } from "@/types/contracts"

interface ActivitySummaryProps {
  analyticsEnabled: boolean
  isGenerating: boolean
  lastGeneratedAt: Date | null
  summary: SummaryResult | null
  error: Error | null
  onGenerate: () => void
}

function formatWindowTime(value: string): string {
  const parsed = new Date(value)

  if (Number.isNaN(parsed.getTime())) {
    return value
  }

  return parsed.toLocaleTimeString()
}

export function ActivitySummary({
  analyticsEnabled,
  isGenerating,
  lastGeneratedAt,
  summary,
  error,
  onGenerate,
}: ActivitySummaryProps) {
  const knockCount = summary?.counts.knock ?? 0
  const doorbellCount = summary?.counts.doorbell ?? 0

  return (
    <Card>
      <CardHeader>
        <CardTitle>
          Recent activity — generated by Snowflake AI
        </CardTitle>

        <CardDescription>
          Generate an AI summary of detection activity from
          the last 30 minutes.
        </CardDescription>
      </CardHeader>

      <CardContent className="space-y-4">
        <Button
          onClick={onGenerate}
          disabled={isGenerating || !analyticsEnabled}
        >
          {isGenerating
            ? "Generating Summary..."
            : "Generate Summary"}
        </Button>

        {!analyticsEnabled && (
          <p className="text-sm text-muted-foreground">
            Enable analytics and cloud storage in settings
            to generate AI summaries.
          </p>
        )}

        {summary && (
          <div
            className="space-y-3"
            aria-label="Activity summary"
          >
            <p className="text-sm">{summary.text}</p>

            <dl
              className="flex gap-6 text-sm"
              aria-label="Exact detection counts in the summary window"
            >
              <div>
                <dt className="text-muted-foreground">
                  Knock
                </dt>
                <dd className="font-medium">{knockCount}</dd>
              </div>
              <div>
                <dt className="text-muted-foreground">
                  Doorbell
                </dt>
                <dd className="font-medium">
                  {doorbellCount}
                </dd>
              </div>
            </dl>

            <p className="text-sm text-muted-foreground">
              Window: {formatWindowTime(summary.since)} to{" "}
              {formatWindowTime(summary.through)}
            </p>

            <p className="text-sm text-muted-foreground">
              {summary.model
                ? `Generated by ${summary.model}`
                : "No AI model was used because no permitted events were in the window."}
            </p>
          </div>
        )}

        {lastGeneratedAt && (
          <p className="text-sm text-muted-foreground">
            Last generated{" "}
            {lastGeneratedAt.toLocaleTimeString()}
          </p>
        )}

        {error && (
          <p
            className="text-sm text-destructive"
            role="alert"
          >
            Unable to generate activity summary.
          </p>
        )}

        {!summary && !lastGeneratedAt && !error && (
          <p className="text-sm text-muted-foreground">
            No AI summary has been generated yet.
          </p>
        )}
      </CardContent>
    </Card>
  )
}
